### ISSUE TITLE
Gperms bug

### ISSUE THREAD

**Issue by TacoLord321** [DiscordDungeons/Bugs#871]
**Describe the bug**
If player A transfers ownership of guild to player B, doing #!gperms will display both as owner. Doing #!guild will show current owner

**To Reproduce**
Be guild owner, transfer guild, both parties will show as owner 

**Expected behavior**
Gperms to display sames roles as guild. Screenshot shows gmembers Lister 2 owners 1 elder and guild 1 owner, 2 elders

**Screenshots**
![Screenshot_20191122-064450](https://user-images.githubusercontent.com/48126615/69423598-7ef8a780-0cf4-11ea-8169-a738e5347862.png)

**Comment by Willard21** [comment]
Huh. Interesting. Seems transferring ownership lets you keep all the perms of owner. Of course the non-owner can't actually disband the guild, so I guess I could manually toggle that perm off when someone gives up ownership.

The gperms thing is just showing the name of the role that matches each player's perms, so the previous owner has Owner perms. You can give them the elder role to fix if you'd like.

**Comment by Willard21** [comment]
Updated gmembers to gperms everywhere since you were talking about the gperms command.

**Comment by Sven65** [comment]
Seems like this has been fixed in some other patch.

**Comment by Willard21** [comment]
![image](https://user-images.githubusercontent.com/24826881/101801918-7b3cec00-3ad4-11eb-92b7-fbaa9d15adbf.png)
Nope still present.

**Comment by Sven65** [comment]
Alright, is that reproducable, or is it just that specific guild?
